version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node16.14.0-chrome99-ff97'
workflows:
  build:
    jobs:
      - cypress/run:
          executor: with-chrome
          browser: chrome
          record: true
