version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout
      - run: node --version
      - run: # print the name of the branch we're on
          name: "What branch am I on?"
          command: echo "${PWD}"
      - run: # print the name of the branch we're on
          name: "List files"
          command: ls